global:
  enabled: false 
server:
  enabled: false
injector:
  enabled: true
  namespaces: ["default"] # namespace to inject into
  extraEnv:
    - name: AGENT_INJECT_VAULT_ADDR
      value: https://my-vault.example.com:8200
  serviceAccount:
    name: my-vault-auth
