apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      containers:
      - name: vault-agent
        image: hashicorp/vault
        command: ["sh", "-c", "vault agent -config=/etc/vault.d/vault-agent.hcl"]
        env:
        - name: VAULT_ADDR
          value: "https://hcvault-sandbox.llm-aws.com:8200/"
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault.d
        - name: webrender
          mountPath: /home/vault/
      volumes:
      - name: vault-config
        hostPath:
          path: /path/on/host/vault-config
      - name: webrender
        hostPath:
          path: /path/on/host/WebRender
