apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        vault.hashicorp.com/agent-inject: 'true' 
        vault.hashicorp.com/role: 'juan-vault-web-poc'  
        vault.hashicorp.com/agent-inject-status: 'update'  
        # vault.hashicorp.com/auth-path: 'auth/kubernetes'  
        vault.hashicorp.com/auth-path: 'auth/docker-desktop'
        vault.hashicorp.com/namespace: 'default' 
    spec:
      serviceAccountName: juan-vault-web-poc  
      containers:
      - name: web-app
        image: bacus/webjsvaultproject:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "356Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /vault/configs
      volumes:
      - name: config-volume
        configMap:
          name: web-app-vault-template-configmap