apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "juan-web-poc-policy"
        vault.hashicorp.com/agent-inject-secret-appconfigs.json: "devops/kv/vault-templating-poc"
        vault.hashicorp.com/agent-template-configmap: "web-app-vault-template-configmap"
        vault.hashicorp.com/agent-template-file: "appconfigs.json.tpl"
        vault.hashicorp.com/agent-inject-template-file: "/app/configs/appconfigs.json"
        vault.hashicorp.com/agent-template-wait-min: "15s"
        vault.hashicorp.com/agent-template-wait-max: "5m"
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: web-app
          image: bacus/webjsvaultproject:latest
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"