apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-render
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-render
  template:
    metadata:
      labels:
        app: web-app-render
    spec:
      containers:
      - name: web-app-render
        image: bacus/webjsvaultproject:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck 
            port: 3001
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck 
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: web-app-config-volume
          mountPath: /app/configs/appconfigs.json
          subPath: appconfigs.json
      volumes:
      - name: web-app-config-volume
        configMap:
          name: web-app-config
