apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-render
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-render
  template:
    metadata:
      labels:
        app: web-app-render
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "web-app-render"
        vault.hashicorp.com/agent-inject-secret-appconfigs.json: "devops/kv/vault-templating-poc"
        vault.hashicorp.com/agent-inject-template-appconfigs.json: |
          {{ with secret "devops/kv/vault-templating-poc" }}{{ .Data.data | toJSONPretty }}{{ end }}
    spec:
      serviceAccountName: web-app-render
      containers:
      - name: web-app-render
        image: bacus/webjsvaultproject:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: vault-template-configmap
          mountPath: /vault/secrets
          readOnly: true
      volumes:
      - name: vault-template-configmap
        configMap:
          name: vault-template-configmap