apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-08-25T20:51:13Z"
  name: vault-auth
  namespace: default
  resourceVersion: "70155"
  uid: 5293dc89-0b50-421a-bb8b-6916f50f547b
secrets:
- name: vault-auth-secret