# helm-values.yaml
global:
  enabled: false  # Disable all components by default

  # Specify the Vault address
  vaultAddress: "https://hcvault-sandbox.llm-aws.com:8200"

# Disable the Vault server component
server:
  enabled: false

# Enable and configure the Vault Agent Injector
injector:
  enabled: true

  # Specify the Vault address for the injector
  extraEnv:
    - name: VAULT_ADDR
      value: "https://hcvault-sandbox.llm-aws.com:8200"

  # Service Account to use; make sure this SA has the necessary permissions
  serviceAccount:
    name: "vault-auth"