apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    app: web-app-render # This should match the labels of your web app pods
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001 # This should match the port your web app is listening on
